version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dinningdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dinningdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dinningdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres

volumes:
  postgres_data:
